### ISSUE TITLE
Unbale to see stock_cancel in my modules list

### ISSUE THREAD

**Issue by lapagept** [OCA/stock-logistics-workflow#109]
Hello guys,
Is this something special I should know about stock_cancel? Unable to see this module in module list. I have proceeded Like usuallly... Permission, owner checked... 
What is the problem...
Help pleasae

**Comment by yvaucher** [comment]
Please see #59 

stock_cancel is disabled in `__openerp__.py` as it was dangerous in 8.0

**Comment by lapagept** [comment]
So, I imagine it is better to wait before to retry it. Thanks
