### ISSUE TITLE
Translation issue on stock_no_negative  fr

### ISSUE THREAD

**Issue by luffah** [OCA/stock-logistics-workflow#1094]
Hello,

(minor issue - not directly linked to the code)

Special chars are converted to `??` in `stock_no_negative/i18n/fr.po`
https://github.com/OCA/stock-logistics-workflow/blob/17b3425f30abc82e48267777967c182d30a54bb9/stock_no_negative/i18n/fr.po

Note : Below sed/vim  substistutions to clean the text.
```vim
%s/\CCat??gorie/Catégorie/g
%s/\Ccat??gorie/catégorie/g
%s/attach??/attaché/g
%s/Mod??le/Modèle/g
%s/n??gati/négati/g
%s/op??ration/opération/g
%s/activ??/activé/g
%s/bloqu??/bloqué/g
%s/ ?? / à /g
```

**Comment by pedrobaeza** [comment]
Please go to Weblate (you can do it through the badge of the README) and change it accordingly.

**Comment by luffah** [comment]
Done (2 minutes on vim, 15 min on weblate... no search replace feature found)
