### ISSUE TITLE
Feature request : "lock" lots/serial numbers

### ISSUE THREAD

**Issue by clonedagain** [OCA/stock-logistics-workflow#110]
We and others have the need to "lock" arbitrary serial numbers/production lots for various reasons (usually related to quality control).
Basically, while a lot is locked, no stock move and reservation can be allowed.

**Comment by clonedagain** [comment]
OdooMRP has an implementation of this feature in https://github.com/odoomrp/odoomrp-wip/tree/8.0/mrp_lock_lot .
I'm willing to help improve this module and bring it to OCA, @pedrobaeza would you agree ?

**Comment by pedrobaeza** [comment]
Yeah, of course. This module is ready for OCA.

**Comment by clonedagain** [comment]
@pedrobaeza the README file reads _"Changes in manufacturing, and delivery orders, to selecting the locked bundles is prevented."_ but I see no trace of this in the code.
Is it implemented, or should I add an extra check to prevent users to manually set the serial number to a blocked one ( ie. in the "transfer details" wizard or in the "produce" wizard) ?

**Comment by pedrobaeza** [comment]
This README is a bit outdated. We found a way to lock in all places: modifying the quant get domain, so every operation that uses it (standard does for reserving), doesn't take this quantities into account.

**Comment by clonedagain** [comment]
@pedrobaeza the module doesn't depend on `mrp` anymore.
Would it be OK for you if I drop the dependency and rename the module to `stock_block_lot` ?

**Comment by pedrobaeza** [comment]
OK, I agree. Please put a symbolic link for not loosing current installations.
