### ISSUE TITLE
[15.0] stock_picking_mass_action: Is needed this module for v15??

### ISSUE THREAD

**Issue by sergio-teruel** [OCA/stock-logistics-workflow#1117]
Hi.

After a functional review i think that this module is not needed for v15.
Odoo core already allow to check availability, validate, unreserve for multiple pickings.

![Selección_1505](https://user-images.githubusercontent.com/7689807/198101585-0fa1e485-d21f-4d6b-abe9-d4297e215d6c.png)

@rousseldenis @pedrobaeza @LoisRForgeFlow What do you think about it?

**Comment by legalsylvain** [comment]
If yes, could you make the according PR on openupgrade ?
Thanks !

**Comment by rousseldenis** [comment]
@sergio-teruel There are also Mark as Todo and Check Availability in the wizard action.

**Comment by sergio-teruel** [comment]
Is it an important reason to keep maintaining this module?
For me, no. But if you think otherwise, for me no problem..

**Comment by rousseldenis** [comment]
> Is it an important reason to keep maintaining this module? For me, no. But if you think otherwise, for me no problem..

Through that module life, it has evolved following Odoo core evolutions too (as mass actions changed), so, why not ?

**Comment by sergio-teruel** [comment]
Ok.
So I close this issue
