### ISSUE TITLE
[V14] stock_move_line_auto_fill in componentes of a MO

### ISSUE THREAD

**Issue by FranciscoBigWings** [OCA/stock-logistics-workflow#1129]
## Module
stock_move_line_auto_fill

**Affected versions**: V14

## Describe the bug
In a enviroment where manufactured products and materials used are tracked by lot numbers, in a manufacture order (MO) it is not possible to fill automatically the lot numbers of the materials (already in stock). The components without lot number are filled automatically but not the components tracked by lot number.

When a new manufacture order is created, before making marking it as done, Odoo forces to manually fill the lot number of the components to consume, it doesnt even suggest the existing lot numbers in the inventory for that component.

Is this normal behaviour? In previous version V13, it worked as expected. I experienced the difference of behaviour after upgrading to V14 a DB.

**Comment by rousseldenis** [comment]
@ivantodorovich As you migrated this one, do you have any clue on this ? I see you didn't change the module behavior. So, maybe an Odoo core change

**Comment by ivantodorovich** [comment]
Uhm, unfortunately I've no idea. Possibly a core change as you said.
This module doesn't depend on `mrp` so naturally this case isn't tested.
