### ISSUE TITLE
Missing readme.rst and readme to update

### ISSUE THREAD

**Issue by yvaucher** [OCA/stock-logistics-workflow#114]
- [x] stock_picking_invoice_link #107 (module was not ported) @tafaRU 

To update (not following template, AGPL logo, OCA maintainers, etc):
- [x] picking_dispatch #115
- [x] stock_cancel #116
- [x] stock_dropshipping_dual_invoice #117

**Comment by florian-dacosta** [comment]
I am on it!

**Comment by florian-dacosta** [comment]
Actually, it is already done in this work in progress PR : https://github.com/OCA/stock-logistics-workflow/pull/107

**Comment by yvaucher** [comment]
Thanks for the pointer

**Comment by Doscaal** [comment]
update README.rst for picking_dispatch module PR : #115

**Comment by Doscaal** [comment]
update README.rst for stock_cancel module PR : #116

**Comment by tafaRU** [comment]
All tasks are completed, I close the issue than.
