### ISSUE TITLE
[RFC] Add module to enhance backorder strategy

### ISSUE THREAD

**Issue by rousseldenis** [OCA/stock-logistics-workflow#1191]
As Odoo introduced in v16 the backorder strategy on picking type model, we don't need anymore the stock_picking_backorder_strategy module.

Nevertheless, as we have some needs putting the backorder strategy on partner level and adding some extra stuff, I plan to keep the base module, adding some stock only related stuff on it.

@jbaudoux

**Comment by legalsylvain** [comment]
Hi @rousseldenis. Thanks for the information. If I understand correctly,
-  ``stock_picking_backorder_strategy`` is now native.
- you plan to develop new module regarding other feature.

If yes, could you : 
- make a PR on https://github.com/OCA/OpenUpgrade/blob/16.0/openupgrade_scripts/apriori.py
- use a different name for the new module ? 

Thanks !

**Comment by rousseldenis** [comment]
> * use a different name for the new module ?

@legalsylvain Why do you think a different name should be done as the purpose is to enhance the backorder strategy ?

**Comment by legalsylvain** [comment]
because people using stock_picking_backorder_strategy in v15 will maybe not want to have this module in V16.
Better to explicit with a new name, that feature are totally different.

I also fear that if we don't change the name, that generates some trouble in the migration process, as we have to mention : 
merged : {"stock_picking_backorder_strategy": "stock"}

**Comment by rousseldenis** [comment]
> because people using stock_picking_backorder_strategy in v15 will maybe not want to have this module in V16. Better to explicit with a new name, that feature are totally different.
> 
> I also fear that if we don't change the name, that generates some trouble in the migration process, as we have to mention : merged : {"stock_picking_backorder_strategy": "stock"}

Yes, ok, I will manage that

**Comment by rousseldenis** [comment]
@legalsylvain FYI, I did this: https://github.com/OCA/stock-logistics-workflow/pull/1199

Closing this as no more needed
