### ISSUE TITLE
V14.0 - product_supplierinfo_for_customer_picking - Wrong supplierinfo code

### ISSUE THREAD

**Issue by arbitora** [OCA/stock-logistics-workflow#1192]
In the picking view, it should show product default_code for specific partner_id the picking is set for.

## Module
product_supplierinfo_for_customer_picking

## Describe the bug
Following code is incorrect:
(File in question: [stock-logistics-workflow](https://github.com/OCA/stock-logistics-workflow)/[product_supplierinfo_for_customer_picking](https://github.com/OCA/stock-logistics-workflow/tree/14.0/product_supplierinfo_for_customer_picking)/[models](https://github.com/OCA/stock-logistics-workflow/tree/14.0/product_supplierinfo_for_customer_picking/models)/stock_move.py)
`customer = fields.first(
                    move.product_tmpl_id.customer_ids.filtered(
                        lambda m: move.picking_id.partner_id
                    )
                )`
Should be:
`customer = fields.first(
                    move.product_tmpl_id.customer_ids.filtered(
                        lambda m: m.name == move.picking_id.partner_id
                    )
                )`

## To Reproduce
**Affected versions**: v14

1. Set two different default_codes for product for two different partners.
2. Create sale order for the latter partner (2nd line in default_code listing)
3. Check sale order's delivery order --> it shows the first default_code instead of the specific partner's default_code

**Expected behavior**
Should show the default_code of the specific partner if it had any.

**Additional context**
None

**Comment by rousseldenis** [comment]
Indeed, and it's there from the beginning.

@tafaRU @MiquelRForgeFlow @AaronHForgeFlow Could you confirm and take care of fixing this ?

**Comment by JuanyDForgeflow** [comment]
@rousseldenis https://github.com/OCA/stock-logistics-workflow/pull/1217/

**Comment by rousseldenis** [comment]
@arbitora Could you test the proposed fix ?

**Comment by arbitora** [comment]
> @arbitora Could you test the proposed fix ?

Thank you for the update.
Seems working as intended now with my dataset as well!
