### ISSUE TITLE
[15.0] stock_landed_costs_purchase_auto split method and boolean field is missing

### ISSUE THREAD

**Issue by tv-openbig** [OCA/stock-logistics-workflow#1228]
In v13 there was a field "create_landed_cost_line" (boolean field) and also a field "split_method_landed_cost_line" furthermore a  "active" boolean field. In v15 these fields are missing.

## Module
stock_landed_costs_purchase_auto

## Describe the bug
These fields are missing and i am wondering if creation of landed cost entries will work properly without at least the two fields
 "create_landed_cost_line", "split_method_landed_cost_line"

## To Reproduce
I have checked this on runbot  https://runboat.odoo-community.org/builds?repo=oca/stock-logistics-workflow&target_branch=15.0 by opening:

Inventory > Configuration > Delivery > Shipping Methods
Here i open one of the available shipping methods for example "The Poste".
Both fields are missing in comparison to v13:
https://runboat.odoo-community.org/builds?repo=oca/stock-logistics-workflow&target_branch=13.0. 

Here is v13:
![Bildschirmfoto 2023-02-17 um 10 58 53](https://user-images.githubusercontent.com/8348598/219614369-b20383b4-2f7c-4fde-91b0-efd05e637aa2.png)

Here is v15:

![Bildschirmfoto 2023-02-17 um 10 41 16](https://user-images.githubusercontent.com/8348598/219614740-a97b8524-21c5-4eec-94f7-959f31a7dde6.png)

**Expected behavior**
I assume both fields should be there.

**Additional context**
Maybe it is related to a dependent module ?

**Comment by pedrobaeza** [comment]
That module is `stock_landed_costs_delivery`, not the one migrated. Being handled internally.
