### ISSUE TITLE
[7.0] Duplicate invoice when stock_picking_invoice_link is instaled

### ISSUE THREAD

**Issue by mileo** [OCA/stock-logistics-workflow#126]
When trying to duplicate an invoice with related pickings you are blocked by this constraint.

odoo/addons/stock.py:
class stock_picking
...
    _sql_constraints = [
        ('name_uniq', 'unique(name, company_id)', 'Reference must be unique per Company!'),
    ]

**Comment by eLBati** [comment]
Thanks @mileo 
this https://github.com/OCA/stock-logistics-workflow/pull/128 should fix it

**Comment by pedrobaeza** [comment]
Close as #128 is merged
