### ISSUE TITLE
Feature request: stock_picking_invoice_link, Print the liste of pickings on invoices

### ISSUE THREAD

**Issue by clonedagain** [OCA/stock-logistics-workflow#127]
In France (and probably elsewhere) it's now mandatory to print the delivery date of the goods on invoices.
Since `stock_picking_invoice_link` adds the list of pickings on the invoice form, I suggest we extend stock_picking_invoice_link to print the picking references and delivery dates at the bottom of the invoices.

**Comment by clonedagain** [comment]
We currently have a clumsy implementation of this, not clean enough for OCA but sufficient for us.
If there's enough interest and no-one proposes a patch, we can rewrite our implementation and propose it. Please let @lbellier and I know.

**Comment by pedrobaeza** [comment]
Better than in footer, it can be interesting to group lines by picking, printing a line that acts as group and picking information

**Comment by dcorio** [comment]
@pedrobaeza +1
that's a required feature (mandatory by law) here in Italy.
we actually group the invoice lines by DdT (document of transport), which is the equivalent of the spanish albarán (am i right Pedro?), but the grouping by picking is a must-have IMO.

**Comment by clonedagain** [comment]
OK what about just printing the delivery date of the stock move on each invoice line ?

**Comment by pedrobaeza** [comment]
@dcorio, certainly in spanish it is called "albarán".

@clonedagain, it's better to have all the information (picking number, picking date, and so on), and then you can customize hiding what you want. I know that this is more difficult to achieve, but it's a very common need.

**Comment by ghost** [comment]
I have a v7 module that does this - someone could take it, remove the client specific stuff, and use it.

**Comment by rousseldenis** [comment]
@clonedagain What the status of this? I think as it is very old, it can be closed.
