### ISSUE TITLE
[stock_no_negative] Error raises on subcontracting

### ISSUE THREAD

**Issue by mschulz-asphericon** [OCA/stock-logistics-workflow#1275]
https://github.com/OCA/stock-logistics-workflow/blob/8b71576631315ab184a5fba545dbd705bcc69bd0/stock_no_negative/models/stock_quant.py#L22-L53

This check raises when: 
- you have a product and component configured for subcontracting
- a BOM to define subcontracting
- a subcontracting process with a PO for the finished product, a delivery of the components and a receipt for the finished product
- send the components to the subcontractor
- if you then try to validate the receipt the check raises, because you try to remove the finished products from the subcontracting location, but actually the components are consumed and finished products are added

most likely this is a problem of an incorrect order, where the check raises before the subcontracting was performed

**Comment by pedrobaeza** [comment]
Check https://github.com/odoo/odoo/pull/75065 and https://github.com/OCA/manufacture/pull/878
