### ISSUE TITLE
[16.0][BUG] stock_picking_auto_create_lot : Can't validate and raise backorder wizard

### ISSUE THREAD

**Issue by kanda999** [OCA/stock-logistics-workflow#1281]
## Module
stock_picking_auto_create_lot

## Describe the bug
When I press the validate button on the delivery of a product that has the Auto Create Lot option, the backorder wizard raise and I cannot validate it.

## To Reproduce
**Affected versions**:
16.0
1. Give the product and operation type the Auto Create Lot option.
2. Make an delivery with that product.
3. Press VALIDATE button and apply Immediate Transfer wizard.
4. Raise backorder and auto create doesn't work.
![2023-04-20_19h17_48](https://user-images.githubusercontent.com/101688144/233339377-1038255a-4141-4d30-9f4c-d3991694e2e3.png)
**Expected behavior**
Backorder wizards will not be opened and can received in stock.
**Additional context**
This happens with the latest Odoo code. 

@qrtl

**Comment by rousseldenis** [comment]
@ps-tubtim

**Comment by yostashiro** [comment]
> This happens with the latest Odoo code.

Going through the commit history of Odoo, maybe following commits are related (haven't verified):

[FIX] stock: immediate transfer w/ tracked product
https://github.com/odoo/odoo/commit/3920f1be2ec25433ff1c0dc665ab5149fb75818c

[FIX] stock: validate an immediate transfer without a backorder
https://github.com/odoo/odoo/commit/dd44e1f69dfd217fafa9c2ec5da8b211b2ff3513

@kanda999 Can you try and identify if it is something we should fix in Odoo core or in this module?
