### ISSUE TITLE
cancel meaning of a picking dispatch (functional issue)

### ISSUE THREAD

**Issue by rdeheele** [OCA/stock-logistics-workflow#13]
_Steps_
Create a picking dispatch
Add some moves.
Cancel the picking dispatch

_Identified behavior_
The moves and by extension the picking are cancelled too.

_Expected behavior_
In a functional context, it seems more coherent to "desassociate" moves from the cancelled dispatch, and don't change the move states.

Any opinions?

**Comment by pedrobaeza** [comment]
I'm not so sure this must be intended behaviour. If you want to unlink moves, you just remove the dispatch. This way, you have an option to cancel moves "in batch". I would let this as is, documenting the behaviour exhaustively instead.

**Comment by rdeheele** [comment]
Hi Pedro,
Your remark makes totally sense, but the issue proves that's not first sight evident and I'm thinking, as you propose, about make things clearer (comments, docs, tip...)
