### ISSUE TITLE
Manage goods transportation with containers in ship

### ISSUE THREAD

**Issue by bealdav** [OCA/stock-logistics-workflow#1300]
## Is your feature request related to a problem
no, i just need to manage container transportation overseas in odoo

## Describe the solution you'd like
Make a module with a dedicated object linked to purchase and picking at least

## Describe alternatives you've considered
Use existing concept implemented in modules which I don't found in OCA

Help welcome, Thanks

@jgrandguillaume @rousseldenis @pedrobaeza @eLBati @grindtildeath @gurneyalex @LoisRForgeFlow @jbaudoux

**Comment by jbaudoux** [comment]
Have a look at https://odoo-community.org/shop/shipment-advice-6592#attr=23867
