### ISSUE TITLE
[16.0][BUG] cannot re-assign move after applying inventory 

### ISSUE THREAD

**Issue by nguyenminhchien** [OCA/stock-logistics-workflow#1380]
## Module
stock_move_free_reservation_reassign

## Describe the bug
After [this commit](https://github.com/odoo/odoo/commit/e21c17fae8a29c8ee04883b27d761b8ce13cf5b7) is merged, it cannot re-assign the stock move when applying the inventory in inventory mode.
Because re-assign the stock is going to update the field `reserved_quantity` which is not in allowed fields.

## To Reproduce
Run the tests and it will be failed
![image](https://github.com/OCA/stock-logistics-workflow/assets/8724793/8546aafb-69c6-4731-8b9a-1fecfb9c384a)

**Comment by rousseldenis** [comment]
Closing as comlpeted
