### ISSUE TITLE
[16.0] stock_picking_invoice_link lang po not up to date regarding pot

### ISSUE THREAD

**Issue by mide-dynapps** [OCA/stock-logistics-workflow#1381]
Hi, 

I want to translate fr.po but some words are not in the file.
The synchronization with pot and their lang files is not done and some word can't be translate over Weblate.

Could you help me ?

**Comment by pedrobaeza** [comment]
I don't think so, as there's a POT sync after each merge. Please specify exactly which sentences you can't translate and where they are located to see if the problem is that one.

**Comment by mide-dynapps** [comment]
For example, https://github.com/OCA/stock-logistics-workflow/blob/438a6e663ad63d2d00de15d9f7dcfcc1e11b8a29/stock_picking_invoice_link/i18n/stock_picking_invoice_link.pot#L23

Not found in fr.po

**Comment by pedrobaeza** [comment]
OK, I understand that the problem is in POT > PO sync, not in POT generation. There's also a process for that. @sbidoul do you figure out why they are not synced?

**Comment by sbidoul** [comment]
That process occurs in weblate with the msgmerge addon. It regularly misses some addons, for an unknown reason.

I fixed this one, and I'll launch a mass refresh one of these days.
