### ISSUE TITLE
Module stock_lot_on_hand_first - Maturity Level

### ISSUE THREAD

**Issue by TumbaoJu** [OCA/stock-logistics-workflow#1438]
Hello, we are really interested in the "stock_lot_on_hand_first" module in V14 but the maturity level is still "Alpha" even if the module has been added one year ago.

Can someone confirm that we should not use it for a customer in production until the maturiy level is Stable? or if it is OK ?

Thank you.

**Comment by grindtildeath** [comment]
Hello @TumbaoJu 

The suite of modules (ie this module but also stock_lot_product_qty_search, mrp_lot_on_hand_first) are all used in production by several of our customers.

I'd happily merge a PR setting the development status to stable.

**Comment by TumbaoJu** [comment]
> Hello @TumbaoJu
> 
> The suite of modules (ie this module but also stock_lot_product_qty_search, mrp_lot_on_hand_first) are all used in production by several of our customers.
> 
> I'd happily merge a PR setting the development status to stable.

Thank you!
