### ISSUE TITLE
Picking dispatch: field picker can be empty, the system considers it as assigned

### ISSUE THREAD

**Issue by ybofr** [OCA/stock-logistics-workflow#149]
Steps to reproduce:
1. Create a picking dispatch
2. Add some stock moves
3. Click assign (the field picker is empty, still)
<img width="972" alt="picking_dispatch_-_odoo" src="https://cloud.githubusercontent.com/assets/7601880/9650748/3bffb7b6-51ff-11e5-967b-2e662a9c21c8.png">

<img width="1040" alt="picking_dispatch_-_odoo" src="https://cloud.githubusercontent.com/assets/7601880/9650756/586498e0-51ff-11e5-9bb9-daa270b42bd7.png">

**Comment by rousseldenis** [comment]
@ybofr This is normal. The picker is mandatory when you want to start picking.

I close this as it is very old. Please feel free to reopen it.
