### ISSUE TITLE
picking_dispatch: Short dump of availability check when the stock is not available

### ISSUE THREAD

**Issue by ybofr** [OCA/stock-logistics-workflow#150]
Steps to reproduce

1.Create a material of type stockable material
2. Create a sales order
3. Confirm the sales order
4. Create a picking dispatch
5. Add the newly created delivery order to the picking
6. Save and press availability check
<img width="1126" alt="picking_dispatch_-_odoo" src="https://cloud.githubusercontent.com/assets/7601880/9677329/895cb956-52d0-11e5-8af5-fed36a6096c7.png">

**Comment by rousseldenis** [comment]
#214 is merged, closing
