### ISSUE TITLE
picking_dispatch: cancel does cancel all the moves in the dispatch

### ISSUE THREAD

**Issue by ybofr** [OCA/stock-logistics-workflow#151]
Hi,

Not sure, if it is a feature or a bug. But when I press on cancel, without any warning, all moves are cancelled. I believe in a warehouse environment, this is very difficult to manage and quite dangerous, if a lot of moves are cancelled without warning.

Regards
Eva P.

**Comment by rousseldenis** [comment]
@ybofr You can also use the 'stock_picking_back2draft' module which do what you expect.

I will close this as it is very old. Please feel free to reopen it.
