### ISSUE TITLE
Handling of Variable Weight Items in Multi-Step Warehouse Operations

### ISSUE THREAD

**Issue by rafaelbn** [OCA/stock-logistics-workflow#1510]
Hello! 😄 

#### Abstract

This request for comments (RFC) seeks input on a pressing issue encountered in Odoo v16, involving the handling of variable weight items in multi-step warehouse operations. Specifically, the challenge arises with products that have variable weights (e.g., legs of Serrano ham), where the weight and, consequently, the cost per item can vary significantly. The current system does not adequately propagate updated weights from one step of the operation to the next, leading to discrepancies in customer invoices and delivery notes.

#### Background

In our warehouse configuration, we process orders in 2 and 3 steps, dealing with both fixed weight and variable weight products, measured in kilograms. Variable weight products pose a unique challenge, as exemplified by our handling of Serrano ham legs. These products are priced per kilogram, both for purchasing and sales, but each item's weight can differ. For instance, a customer might order 10 hams, estimated at approximately 50 kilos in total; however, the actual weight can vary upon picking and weighing at the warehouse.

The issue occurs when, after the initial weighing process (where, for example, the actual weight comes to 52 kilos rather than the estimated 50 kilos), this updated weight does not get accurately reflected in subsequent steps. Specifically, the delivery note for the delivery personnel still indicates the original estimated weight (50 kilos), not the actual weight (52 kilos) determined at the picking stage. This discrepancy can lead to billing inaccuracies and operational inefficiencies, as the delivery personnel are not equipped to re-weigh items, and the system does not update the delivery documentation to reflect the actual weights.

#### Problem Statement

The lack of a mechanism to automatically update and propagate the actual weights of variable weight items through all steps of warehouse operations in Odoo v16 leads to inaccuracies in delivery notes and customer invoicing. This situation undermines operational efficiency and can potentially impact customer satisfaction due to discrepancies between estimated and actual delivered weights.

#### Proposed Solution

We are seeking input on potential solutions that could be implemented within Odoo or through custom module development, specifically for the OCA community's consideration. The ideal solution would:

1. Automatically update the delivery order and associated customer invoice to reflect the actual weight of variable weight items once they are weighed during the picking process.
2. Ensure that any adjustments made to the weight and, therefore, the cost of variable weight items are accurately reflected in all subsequent documentation and billing.
3. Facilitate seamless operational flow from warehouse picking to final delivery without requiring manual adjustments or re-weighing by delivery personnel.

#### Request for Comments

We invite the OCA community and other Odoo users to provide feedback, suggestions, and potential solutions to this challenge. Your insights could be invaluable in developing a module or contributing to an existing one that addresses the issues with variable weight items in multi-step warehouse operations.

- How have you approached similar challenges in your implementations?
- Are there existing modules or tools within the Odoo ecosystem that address this issue?
- What potential pitfalls or considerations should we be aware of in developing a solution?

Your input is greatly appreciated as we seek to improve the handling of variable weight products in Odoo warehouse operations.

Best regards,
Rafael
@moduon MT-5085 @Shide @EmilioPascual

**Comment by Shide** [comment]
PR that can solve this: https://github.com/OCA/stock-logistics-workflow/pull/1513

**Comment by rafaelbn** [comment]
Solved in https://github.com/OCA/stock-logistics-workflow/pull/1513
