### ISSUE TITLE
package_preparation: The selection of the partners brings the user and the partner

### ISSUE THREAD

**Issue by ybofr** [OCA/stock-logistics-workflow#152]
Hi,

When I want to select a partner for package preparation, I am not expecting to have all users also in the selection, but rather customers and suppliers.

Best regards
Eva P.

**Comment by rousseldenis** [comment]
In fact, these 'users' are partners too.
I think this is too restrictive, you maybe want to deliver to partners that are not customers or suppliers (depending on the transfer type)

Closing this as it is very old. Please feel to reopen it.
