### ISSUE TITLE
stock_picking_reorder_lines: No number available

### ISSUE THREAD

**Issue by ybofr** [OCA/stock-logistics-workflow#155]
Hello,

I have installed the module, but I do not see the number. I can only drag and drop the lines to reorganise them. This only works when I have a very small delivery. With more than 20 lines, I am not really able to move the last delivery item to the first position.

Thanks for the help/remarks

Eva P.

**Comment by rousseldenis** [comment]
The line number is not visible on form view because it can only be modified with the drag and drop.

I close this as this is a very old issue
