### ISSUE TITLE
stock_transfer_split_multi: Should not split units in half units

### ISSUE THREAD

**Issue by ybofr** [OCA/stock-logistics-workflow#156]
Hi,

I was able to split ONE unit into half a unit, what is wrong from the functional side.

But I have noticed that this is also the case with Odoo. It accepts part of units.

Thanks 

Eva P.

**Comment by rousseldenis** [comment]
I think this is a misconfiguration on product units (you have to  configure Unit with 1 as rounding precision).

I close this as this is very old. Please feel free to reopen it
