### ISSUE TITLE
Bug in wizard Authorized stock Négatif 

### ISSUE THREAD

**Issue by yahiachehaidar2024** [OCA/stock-logistics-workflow#1580]
## Module
The name of the module that has a bug. : stock_no_negative

## Describe the bug
A clear and concise description of what the bug is.:

bug in wizard of the validation of stock négative  in displaying the name of the product and the quantity négative of this product in the Location

![image](https://github.com/OCA/stock-logistics-workflow/assets/162982961/777be31f-daa3-4df1-b4b1-927516126aa9)

## To Reproduce
**Affected versions**: 17.0

1.Open Module  sales and click on Order menu item
2. Create new Sale Order record and Confirm it.
3. Click on delivery button and validate and i will this popup.

**Expected behavior**
Replace the %s with the appropriate data

**Comment by rousseldenis** [comment]
@yahiachehaidar2024 Thanks for this. Could you try the new version ? I have updated the french translation as translation marks have changed.

**Comment by yahiachehaidar2024** [comment]
thanks ,it works Now
