### ISSUE TITLE
Error when creatring new picking with stock_picking_reorder_lines

### ISSUE THREAD

**Issue by danielDomatix** [OCA/stock-logistics-workflow#163]
I'm trying to create a new picking and i have that error: ValueError: max() arg is an empty sequence.

I FIX it adding that line: if picking.move_lines, because the problem is that if yo don't have any line, it's impossible to find a max sequence.

**Comment by pedrobaeza** [comment]
Can you please make a PR with the proposed solution (which is correct)?

**Comment by OpenCode** [comment]
PR: https://github.com/OCA/stock-logistics-workflow/pull/184
