### ISSUE TITLE
[8.0][BUG] stock_dropshipping_dual_invoice - Error bringing payment data to invoice from company and customer

### ISSUE THREAD

**Issue by rafaelbn** [OCA/stock-logistics-workflow#165]
module: stock_dropshipping_dual_invoice
version: 8.0

**Steps to reproduce**

To reproduce this bug you must install also module account_payment_partner: https://github.com/OCA/bank-payment/tree/8.0/account_payment_partner
- Define in you company a Bank account which customer will pay you.
- Choose a product that has a supplier.
- Choose a customer who has defined (or define it) fields:
  - property_payment_term
  - customer_payment_mode
- Create to this customer a Sale Order of the product. Choose in the line the Drop Shipping route, and choose to invoice in delivery.
- Find the automatically generated RFQ, in it specify invoicing on delivery, and validate.
- Open the delivery, transfer it, and click the button to generate the invoice.
- Fill in the wizard. Two invoices will be generated -- one for the customer, one for the supplier.
- You can find the generated customer and supplier invoices from the Sale and Purchase Orders, respectively.

**Current behavior**
- You will check that in the customer invoice:
  - partner_bank_id is empty
  - payment_mode_id is empty
- You will check that in the supplier invoice:
  - partner_bank_id is empty
  - payment_mode_id is empty

**Expected behavior**
- In the customer invoice it must be filled:
  - partner_bank_id with the company bank account
  - payment_mode_id with the res.partner customer_payment_mode
- In the supplier invoide it must be filled:
  - partner_bank_id with the supplier account bank number
  - payment_mode_id with the supplier payment mode

**Comment by rafaelbn** [comment]
ping @JavierIniesta @JMODaERP please check date a opened this issue.

cc @pedrobaeza

**Comment by rafaelbn** [comment]
@pedrobaeza @antespi I'm not sure if you fixed this issue. Do you remember?

**Comment by pedrobaeza** [comment]
Already solved
