### ISSUE TITLE
[BUG] stock_account_product_run_fifo_hook: raise error when validate the delivery order

### ISSUE THREAD

**Issue by AungKoKoLin1997** [OCA/stock-logistics-workflow#1761]
I am creating a migration PR at https://github.com/OCA/stock-logistics-workflow/pull/1676. The CI tests failed due to an issue with stock_account_product_run_fifo_hook, and I suspect this module may not be functioning correctly. I tried testing it in the Runboat environment on the 16.0 branch, and I encountered the issue.

Steps to reproduce:

- Create a product with lot tracking, set its category costing method to FIFO, and enable automated inventory valuation.
- Create a purchase order for this product with a quantity of 5 and receive it with a new lot.
- Create a sales order for this product with a quantity of 5 and deliver it using the created lot.

After these steps, I encountered the issue shown in the attached image. 
I believe the problem may be related to the following proposed commit: https://github.com/OCA/stock-logistics-workflow/commit/c9136445025eb15807f796cb38d93594561f5ec6

<img width="1430" alt="Screenshot 2024-11-12 at 11 33 35" src="https://github.com/user-attachments/assets/ebd8bb88-74b5-4743-9390-8e367eb6aa15">

@qrtl

**Comment by AungKoKoLin1997** [comment]
@AaronHForgeFlow Can you please take a look this issue?

**Comment by AaronHForgeFlow** [comment]
@AungKoKoLin1997 Too bad. I will check. It is not easy to solve, and it seems the core function it refers has been changed also.
