### ISSUE TITLE
Advanced features for blocked lots/serial numbers

### ISSUE THREAD

**Issue by clonedagain** [OCA/stock-logistics-workflow#189]
As a follow-up to #110, we developed the following features which could be proposed to OCA is there is interest:
- [x] restrict blocking/unblocking to a specific group: https://github.com/numerigraphe/stock-logistics-workflow/tree/8.0-stock-lock-lot-group/stock_lock_lot#configuration
- [x] enforce strict blocking, forbidding users to force the move: https://github.com/numerigraphe/stock-logistics-workflow/tree/8.0-stock-lock-lot-strict/stock_lock_lot_strict
- [ ] allow users to move blocked lots inside certain reception locations (quality control area, reception zone...): https://github.com/numerigraphe/numerigraphe-addons/tree/8.0/stock_lock_lot_receipt
- [ ] add a new state "first use" for newly referenced products, and automatically block received lots for these products: https://github.com/numerigraphe/numerigraphe-addons/tree/8.0/stock_lock_lot_firstuse

Each feature is implemented as a module. They can easily have a corresponding checkbox in the warehouse configuration when stock_lock_lot is installed (stock_lock_lot_strict already has it:https://github.com/numerigraphe/stock-logistics-workflow/blob/8.0-stock-lock-lot-strict/stock_lock_lot/models/res_config.py) .
They "work for us" and I expect they'd require only small improvements to meet OCA standards.

If you are interested please post your comments here.

**Comment by clonedagain** [comment]
@pedrobaeza @alfredoavanzosc @oihane @lbellier for your information: some extensions to mrp_lock_lot and stock_lock_lot.

**Comment by pedrobaeza** [comment]
They seems interesting indeed. Go ahead with the PRs and I'll review then!
