### ISSUE TITLE
check_unicity_qty_available fails with unique_lot active when move is split in wizard

### ISSUE THREAD

**Issue by jkrenzer** [OCA/stock-logistics-workflow#190]
Odoo: 8.0 (git)
Module: product_unique_serial 8.0.1.0.1 (git branch 8.0)

Problem: 
When a picking with quantity N > 1 is received with unique_lot set and the move is split up into single itmes in the move-wizard with the native button to assign unique serial numbers, function check_unicity_qty_available fails with "Product X has active 'unique lot' but with this move you will have a quantity of N in lot Y". Executing the move is blocked.

Expected behavior:
product_unique_lot takes into account changes to move-lines inside the move-wizard and move succeeds.

**Comment by jjscarafia** [comment]
:+1: Same error
I believe it is solved by https://github.com/OCA/stock-logistics-workflow/pull/213
Please test and review it

**Comment by jkrenzer** [comment]
As far as I can see, it works now. Thank you. :)
