### ISSUE TITLE
How can I delete Stock Move in 'Done' state?

### ISSUE THREAD

**Issue by Mitconsulting** [OCA/stock-logistics-workflow#191]
How can I delete Stock Move in 'Done' state?

**Comment by Mitconsulting** [comment]
How to remove a sale order in "done" state?

**Comment by ehahouimohssine** [comment]
ODOO prevents you removing a stock move that the status Done has (For accounting reasons). If you have accidentally put something on done. You must correct this by creating a new stock move. It makes easier to track the sock moves. If you, for some reason want to remove the stock moves, you can remove it from the database through an SQL command. (This is not recommended)

This is also for sales order which has the status done.

**Comment by pedrobaeza** [comment]
This is not an issue of the repository, so I close. Please make the questions in Odoo forums.
