### ISSUE TITLE
[8.0] stock_split_spicking Why is only allowed to split outgoing or incoming shipment ?

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/stock-logistics-workflow#196]
I would like to split internal shipment.

**Comment by Cedric-Pigeon** [comment]
@gurneyalex Do you have an opinion ? Thanks

**Comment by gurneyalex** [comment]
@Cedric-Pigeon feel free to submit a PR for this :smile_cat:

**Comment by Cedric-Pigeon** [comment]
@gurneyalex Done: https://github.com/OCA/stock-logistics-workflow/pull/264

**Comment by pedrobaeza** [comment]
Closing as solved
