### ISSUE TITLE
module: stock_dropshipping_dual_invoice version: 8.0

### ISSUE THREAD

**Issue by sdalexander** [OCA/stock-logistics-workflow#217]
Hi
My name is steve alexander and I am an Odoo ready partner from the UK.

I have installed the module: stock_dropshipping_dual_invoice v8.0 for a client  to manage stock direct delivery from a supplier to a customer and to raise both the supplier and the customer invoices.

I have followed the settings recommended in the module however, when I check both Invoices that it has produced, I find that the sales invoice is correct but the purchase Invoice has used the sale price and Sale VAT(ST0) code rather than the supplier price and the Purchase VAT code( PT0).

Do you have any ideas what has caused this?

the sales order and the Purchase order are both correct the PO has the purchase price from the supplier record and has PT0 as the Tax code.

regards

Steve

**Comment by pedrobaeza** [comment]
Please reproduce it on runbot, and put the steps made to get to that error.

**Comment by sdalexander** [comment]
HI pedro
I have tested on runbot and it works fine, so I have traced it to another module that has been written for the client that must be affecting the production of the Invoice.
I will close this issue
thanks
