### ISSUE TITLE
[8.0] [stock_picking_back2draft] Sale order DONE instead of OPEN

### ISSUE THREAD

**Issue by sandrafig** [OCA/stock-logistics-workflow#229]
**Module:** stock_picking_back2draft

**Steps to reproduce:**
1. Create a sale order for 100 units of any product.
2. Transfer 50 units of product.
3. Cancel the transfer of the 50 remaining units.
4. Click on picking Back to draft.
5. Mark as To Do.

**Problem:**
- The sale order is in state "DONE" even though the picking is not done.
- Invoice control on the picking is Not Applicable.

**Expected behaviour:**
- The sale order moves back to state OPEN as the shipping is not completely done yet.
- Invoice control should be To Be Invoiced.

**Comment by rousseldenis** [comment]
@sandrafig Can you provide which version do you use ?
We will close this as it is very old

**Comment by rousseldenis** [comment]
@sandrafig Checked this on runbot. That flow works as expected. Closing
