### ISSUE TITLE
Calculate qty_available takes a lot of time

### ISSUE THREAD

**Issue by fedexin40** [OCA/stock-logistics-workflow#273]
Hello everyone, @pedrobaeza 

I am using the module stock_filter_none_zero_qty in v7. But apply "Real stock" filter takes a lot of time for finishing.

An looking for the main cause of the problem I noticed that in https://github.com/OCA/stock-logistics-workflow/blob/7.0/stock_filter_none_zero_qty/product.py#L59, the operations are made including all items. But the function does not care if there is a limit value or and offset value at the moment of returning the result.

Then I was wondering ... is there a way to pass at the function what is the limit value and the offset value? Maybe with the new api? or to accomplish it from other way?

Thanks in advance

**Comment by pedrobaeza** [comment]
I'm afraid there's no better way to handle this, as at that level you don't know any other argument/domain that can help you to limit the search. What you can do is to switch the field to an store field, but the difficult thing is to create the correct store triggers that update the quantity when needed.

My best advice here is to migrate to version 8 as soon as possible.

**Comment by fedexin40** [comment]
@pedrobaeza  thanks for your help and advice
