### ISSUE TITLE
[9.0] [stock_picking_invoice_link] Previous customer invoice linked to backorder DO

### ISSUE THREAD

**Issue by dedisinaga** [OCA/stock-logistics-workflow#292]
Module : stock_picking_invoice_link for version 9.0

Suppose I have 1 SO with 1 kind of product with qty=3. 
I create Invoice from sales order partially (eq. 2), for eq. INV-0001
Then I release the DO partially using 2 quantity, with back order (WH/OUT/0001 as delivered and WH/OUT/0002 as available), INV-0001 is still linked into WH/OUT/0002.

This is not the correct way I think. In WH/OUT/0002 there should be no INV-0001. CMIIW

Thank you.

**Comment by pedrobaeza** [comment]
If the behavior is the described, indeed you're right. Can you provide a PR with the fix?

**Comment by dedisinaga** [comment]
I am trying to find the correct way too. If I can solve this, I will submit the PR. 
Thanks
