### ISSUE TITLE
partner_credit_limit

### ISSUE THREAD

**Issue by max3903** [OCA/stock-logistics-workflow#324]
At @ursais, we have a module to block the delivery order if the customer is over his credit limit.

This repo seems like the best fit to host it.

Any feedback?

**Comment by JordiBForgeFlow** [comment]
See this:
https://github.com/OCA/sale-workflow/pull/434

I think that the block should occur ay sales order level, not delivery order. Sometimes you want to ship products to the customer and not be blocked by the credit limit. Like in RMA.

It would be cool to build on top of sale_delivery_block, blocking the sales order when the customer has exceeded the credit limit. Then only a manager or accounting can release the block after reviewing the case.

**Comment by pedrobaeza** [comment]
@jbeficent see my comments on the PR that modules overlapping functionality are already proposed by us before.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza do you mean https://github.com/OCA/sale-workflow/pull/434#issuecomment-292292471?

**Comment by pedrobaeza** [comment]
Actually I mean https://github.com/OCA/stock-logistics-workflow/pull/325#issuecomment-296318600
