### ISSUE TITLE
[BUG] stock_deposit: missing method in model

### ISSUE THREAD

**Issue by cubells** [OCA/stock-logistics-workflow#330]
When you browse to a product form from within another model and click on smart button "in deposit",

![prova01](https://cloud.githubusercontent.com/assets/4386443/26023644/6a273d72-37c1-11e7-8bbe-bbdd449c9b7f.jpg)

an error is raised because method is missing:

![prova02](https://cloud.githubusercontent.com/assets/4386443/26023653/7ad5d7dc-37c1-11e7-835f-b7b79838e30a.jpg)

**Comment by pedrobaeza** [comment]
cc @sergio-teruel

**Comment by pedrobaeza** [comment]
Already solved
