### ISSUE TITLE
many sentinel users

### ISSUE THREAD

**Issue by wkharrat** [OCA/stock-logistics-workflow#346]
Hi,

we use sentinel.py with scaners, when the number of users reaches 70 the system begin to slowdown, if i restart odoo service everything ok, i have db and python in separate servers. How can i fix this?

Regards

Walid

**Comment by rousseldenis** [comment]
We use sentinel for years, but without this amount of users.
The system is quite stable and fast.
Maybe you should look into processes and memory usage, your problem description is a little bit vague.

**Comment by rousseldenis** [comment]
@wkharrat Any news from this ?

**Comment by wkharrat** [comment]
Thanks for your replay, finally we use multiple python servers and every 40 users connected to 1 server
