### ISSUE TITLE
[Question][product_serial] Migration to 8.0

### ISSUE THREAD

**Issue by moylop260** [OCA/stock-logistics-workflow#35]
Hello,
We like migrate to 8.0 of module: product_serial
We need to know what is the guidelines for migration.
 -Use new api or use old api without problems.
 -Stock has important changes and probably refactory of this module is required.

Can you help me with guidelines of this case?

**Comment by pedrobaeza** [comment]
Hi, Moisés,

You can use new API if you want, but it's not mandatory. The rest of the conventions to apply you know what they are, because we have been discussing them through maintainer-quality-tools PRs.

**Comment by moylop260** [comment]
Ok
I got it
Thank you
