### ISSUE TITLE
Stock Move Backdating Upgradation for Odoo 10c

### ISSUE THREAD

**Issue by usmanfarzandali** [OCA/stock-logistics-workflow#355]
Please Upgrade Stock Move Backdating for Odoo 10c

**Comment by pedrobaeza** [comment]
Sorry, but this is not a wishlist. The module will be migrated when someone voluntarily contribute with that migration, or is somebody pays someone for doing that migration.

**Comment by tafaRU** [comment]
@odoogit, see https://github.com/OCA/stock-logistics-workflow/pull/426 and please review it.
