### ISSUE TITLE
[9.0 and 10.0] Default quantities on picking transfer

### ISSUE THREAD

**Issue by chrisdec** [OCA/stock-logistics-workflow#360]
Hello, 

Some of our customers complain about picking's transfer in Odoo 10. 

In version 8.0, when you click "transfer" on a picking, you have a new window with the scheduled quantity for each product line.  So if you schedule to transfer 50 products but you receive only 49 products, you only change quantity of the missing product on the new window and you click "apply". 

Now, in version 9 or 10, if you schedule to transfer 50 products and only receive 49 products, you have to change the quantity directly on the picking. As the quantity by default is 0 for each line, you have to write the received quantity on 49 lines. 

We (Acsone) so would like to create a module to put the same system than in version 8.0. When you click “validate”, a window is opened with the scheduled quantity for each product line. The user only has to change the line(s) for which scheduled quantity is different. 

What do you think? Do you have comments about it? 

Thanks in advance,

**Comment by pedrobaeza** [comment]
I prefer that it simply put by default the full quantities instead of changing the flow.

**Comment by chrisdec** [comment]
Yes, it was our first idea but @lmignon is afraid that maybe users will click "validate" without check the quantities.

**Comment by pedrobaeza** [comment]
You can include in the button the attribute `confirm="Are you sure the quantities are correct?"` or something similar to reinforce the previous check.

**Comment by rousseldenis** [comment]
I think the flow in v10 was quite better (I hope it will be completed in v11).

- The standard mechanism will ask you first if you want to transfer the whole quantities if you didn't change any line.

- If you change one line quantity, indeed, you have to enter quantity on each line.

- In that case, I'd prefer a button on the top of lines (pack operations) that fill the scheduled quantities (without wizard).

Even if I understand the needs, I'd prefer the operator entering the quantities on each line to be sure there is no error. You can have in mind that if in the workflow, the operator has to be interrupted during the transfer, he can interrupt the lines quantities filling in by validating the picking. The remaining quantities will go in a backorder and he can continue the operation later.

**Comment by pedrobaeza** [comment]
Yeah, the button is a great idea also, although as said, there are other possibilities with standard, like making a backorder of only the not completed line, and then another directly with the rest. The only missing workflow is when you have a mix of not received/sent lines, half lines and full lines.

**Comment by rousseldenis** [comment]
That 'missing' workflow can be done through pushing the button 'Fill scheduled quantities' and then change the quantities for the half rest lines ;-)

**Comment by pedrobaeza** [comment]
Indeed

**Comment by zakiuu** [comment]
couldn't agree more and I've done something similar for a client with the packs

**Comment by sbidoul** [comment]
So last question is how to name this module?

**Comment by pedrobaeza** [comment]
`stock_picking_all_done_button`?

**Comment by rousseldenis** [comment]
I'd prefer stock_pack_operation_fill_quantities (for v10)

**Comment by pedrobaeza** [comment]
Then use the singular form in any case: `stock_pack_operation_fill_qty`. I don't like a lot this name, but you decide.

**Comment by zakiuu** [comment]
maybe `stock_pack_operation_auto_fill`?

**Comment by lmignon** [comment]
:+1: for stock_pack_operation_auto_fill

**Comment by zakiuu** [comment]
I've just created a 9.0 PR for this issue, your feedback is more than welcome, thx!

**Comment by rousseldenis** [comment]
@chrisdec solved ?

**Comment by chrisdec** [comment]
yes :)
