### ISSUE TITLE
Transfer date (date_done) of stock_picking calculated when splitting 

### ISSUE THREAD

**Issue by comansa** [OCA/stock-logistics-workflow#375]
When use the "split button" on an stock picking, the transfer date (date_done) of the original one is calculated, even if its in an not in "Transferred state".
Furthermore, when it is transferred using the "transfer button", it doesn´t calculate the correct date.

**Comment by rousseldenis** [comment]
@comansa Could you explain in which environment (version) you are and which modules are involved ?

It's a little bit tricky to guess what problem you face.

**Comment by comansa** [comment]
Yes, of course. It happens when using the module "stock_split_picking" in an Odoo v8 system

**Comment by rousseldenis** [comment]
I've just tested on runbot. The date_done is never filled in when splitting.

I close this. Please feel free to reopen it.
