### ISSUE TITLE
RFC: new module stock_reservation_condition to avoid automatic booking of quants in some conditions

### ISSUE THREAD

**Issue by jcdrubay** [OCA/stock-logistics-workflow#386]
We are going to create this module and submit to OCA for version 10.
Please share your thoughts if you think that design can be improved and therefore benefit more people or let us know if you know a some module already doing this.
Thanks in advance for your contributions.

# The idea/ objective
Change the mechanism of reservation of products when the user confirms the quotation/ SO and when the scheduler runs so products can be kept available in case they are not needed immediately or to wait for a Purchase order to be received (avoiding other delivery due to a partially booking that blocks the partially available order anyway).

# Technical description for Definition of the reservation

Quotation/ SO adjustments:
- in header:
  - Add field "Reservation Date" under Expected date of delivery (manual input) 
- Add tab "Related POs" with a new m2m field `reservation_po_ids` 
and display only 2 columns:
  - PO number 
  - Reservation Date: a new field on PO, computed as latest date of related incoming shipments

Rename the status in stock move ("Waiting Another Move") and stock picking ("Waiting Another Operation") with a suffix "or PO Reception or SO Reservation Date".

# Expected Behavior
If sale_order.reservation_date is set or sale_order.reservation_po_ids has 
some values:
 - the reservation of these products is **not** done when user confirms the SO
 - the reservation will be done by the scheduler
   - if the SO is linked to a PO, for each product listed in the SO:
     - The system will look for the product in on of the reservation_po_ids which is already received: 
       - if it is found, the products (stock.quant) will be reserved
   - otherwise, if the SO is not linked to a PO and has a reservation_date:
     - if the so.reservation_date is reached, then reserve the product  
Otherwise, we proceed as normal:
 -  reservation will take place when the user confirms the quotation/SO

# Technical  Solution to adjust the booking mechanism
Override stock_move.action_assign:

pseudo-code:
```python
if not move.so.reservation_date and len(move.so.reservation_po_ids) ==0:
    pass  #  continue the function action_assign
elif move.product_id in \
          move.so.reservation_po_ids.last_picking_id.filtered(state=Done).\
          lines.product_id:     
    pass  #  continue the function action_assign
elif move.so.reservation_date < today():
    pass  #  continue the function action_assign
else:
    return False
```
   
# Notes
- Reservation Date on the SO has no impact if a product is part of one of the reservation_po_ids

**Comment by rousseldenis** [comment]
@jcdrubay Is this still relevant ?

**Comment by jcdrubay** [comment]
We have done the module and we will submit it when we have time. Whoever needs it, let us know and we will speed-up the release process. Regards, JC

**Comment by JordiBForgeFlow** [comment]
Hi, this is very interesting, and we might neef it for ddmrp. Could you
publish your latest code?

**Comment by rousseldenis** [comment]
@jcdrubay

**Comment by jcdrubay** [comment]
We will try to publish asap :) Do you think you may need it for the current Code Sprint?

**Comment by rousseldenis** [comment]
No, that's because this is some months old. Just to have heartbeat :smile:

**Comment by jcdrubay** [comment]
Actually, we had published it for a while: https://github.com/OCA/stock-logistics-workflow/pull/387/files

**Comment by jgrandguillaume** [comment]
As the PR is merged, I'm clean up this one.

Nbote we have another work that target kind of similar needs: https://github.com/OCA/stock-logistics-warehouse/pull/709
