### ISSUE TITLE
[11.0][stock_no_negative] bug while Receipts product

### ISSUE THREAD

**Issue by fanha99** [OCA/stock-logistics-workflow#391]
reproduce:
- in the inventory, create a Receipts
- add a product to receive
- because you couldn't edit "Initial Demand" value, so it will always zero.
- edit the done value, 10 for example
- save and validate, it will always show up the negative stock error

**Comment by fanha99** [comment]
@etobella, could you please help to check?

**Comment by etobella** [comment]
You are right. The problem is that it is checking the vendor location place for no negative stock and it shouldn't be checked. Today, I will make a PR in order to solve this problem.
Thanks for the issue 👍

**Comment by rousseldenis** [comment]
@etobella,  @fanha99 Is this also on 10 ? Refer to https://github.com/OCA/stock-logistics-workflow/issues/406

**Comment by meigallodixital** [comment]
Is there any blocking issue with the PR on OCB v11?
Seems to build for OCB but not for Community.
Is it OK to go for OCB V11?

**Comment by pedrobaeza** [comment]
@meigallodixital AFAIK, this has nothing to do with OCB.
