### ISSUE TITLE
stock_available_unreserved error when access Product Form

### ISSUE THREAD

**Issue by samy-m-dev** [OCA/stock-logistics-workflow#394]
Since last commit https://github.com/OCA/stock-logistics-warehouse/commit/e6a5a0dbbf3cac8fdcdd8ba426d78f71189e2419

We have an error when opening the product form:

KeyError on qty_available_not_res
qty = res[tmpl.id]['qty_available_not_res']

**Comment by rousseldenis** [comment]
@webtekindo @lreficent There is an improvement in computing available quantities with https://github.com/OCA/stock-logistics-warehouse/pull/305

I think the problem you are describing is solved there.

Can you test it ?

**Comment by JordiBForgeFlow** [comment]
@mreficent Can you review?

**Comment by MiquelRForgeFlow** [comment]
I tested on runbot the https://github.com/OCA/stock-logistics-warehouse/pull/305 and it's true that the problem described here is solved there.

**Comment by rousseldenis** [comment]
@mreficent @jbeficent @Cedric-Pigeon Can we move forward on that PR to improve stability on available quantities computation ?

**Comment by lmignon** [comment]
@rousseldenis OCA/stock-logistics-warehouse#305 LGTM

**Comment by LoisRForgeFlow** [comment]
https://github.com/OCA/stock-logistics-warehouse/pull/305 is merged.
