### ISSUE TITLE
[10.0][stock_no_negative]This is bug?or configure error?

### ISSUE THREAD

**Issue by jaronemo** [OCA/stock-logistics-workflow#401]
produce this error:
1. product A ...100 on hand ...on the  WH/Stock/1D52 
2.stock.picking create ..origin location: WH/Stock, Dest location: Virtual/Customer, qty 60
3.if reserve, stock.move ...origin location is change to WH/Stock/1D52.
4.if user change this locaiton 1D52 to WH/Stock or other sub location...and validate this stock.picking
5. product A on WH/Stock/1D52 is 100....Wh/Stock is -60 

Under normal circumstances, it should be to prevent any negative inventory caused by the operation
.
And I went to debug the code, all have direct access to this code to stop.

  if not check_negative_qty:
            return

Alaways ..run to this return.....

**Comment by pedrobaeza** [comment]
This is because you are trying in test mode, and this is disable in that mode.

**Comment by jaronemo** [comment]
disable ？how to do?

**Comment by pedrobaeza** [comment]
Don't add --test-enable to your server.

**Comment by jaronemo** [comment]
Dear sir:
thank you!..
But... i only use this command : 
![image](https://user-images.githubusercontent.com/8476734/35212851-813b878c-ff96-11e7-9362-6d5856c2bf9e.png)

**Comment by pedrobaeza** [comment]
Then it should work correctly.

**Comment by jaronemo** [comment]
Dear Sir:
Yes... is should work correctly..
But...always is go to test mode.....
