### ISSUE TITLE
Stock Disallow Negative does not work out

### ISSUE THREAD

**Issue by ccandito** [OCA/stock-logistics-workflow#406]
Dear All,
I've implemented it and negative stock occurred.
Regards
claudio Candito

**Comment by rousseldenis** [comment]
Hi,

Could you please give some details about your environment:

The module version you use and please describe exactly the use case you
have.


Le 1 mars 2018 7:54 PM, "Claudio Candito" <notifications@github.com> a
écrit :

**Comment by ccandito** [comment]
Dear Denis,
I'm working on Odoo 10 and the app version is 10.0.1.0.0.
One of the business case I did is to deliver from sales order 100 pcs with 93 on stock.
After forcing the availability, the goods movement has been performed and the stock has became -3 pcs.
Regards
claudio candito

**Comment by HaraldPanten** [comment]
Hi Denis, Claudio,

I've been trying this module as well but I couldn't make it work. I'm using Odoo 10.0-20180303 (Community Edition).

1- I created a stockable product (product A) without stock. Stock 0.

2- The "Allow Negative Stock" checkbox was NOT selected in both options. Product form and Product category.

3- I created a Quotation, I tried to sell 10 units of product A and I confirmed the SO.

4- A Delivery order was generated. 10 units from our stock to the customer's location.

5- I forced availability and I could move these 10 units to the customer's location, so... I have now -10 units of product A.

*****Suggestion:*****

- Claudio: Maybe you could try this module. I've been using it and I think this one could satisfy your needs.

deltatech_stock_negative
https://www.odoo.com/apps/modules/10.0/deltatech_stock_negative/

- Denis: Maybe you could have a look to the module I suggested as well. It could be useful to get some ideas.

Thanks!

**Comment by rousseldenis** [comment]
Tested on runbot and confirmed.

@alexis-via Do you have time to look at this ?

**Comment by pedrobaeza** [comment]
This condition for tests can be disturbing things: https://github.com/OCA/stock-logistics-workflow/blob/10.0/stock_no_negative/models/stock_quant.py#L19

**Comment by rousseldenis** [comment]
@pedrobaeza Agree.

As it is a critical process, we have to ensure this works as expected.

**Comment by ccandito** [comment]
thanks a lot
claudio

2018-05-04 13:08 GMT+02:00 Harald Panten <notifications@github.com>:

**Comment by pedrobaeza** [comment]
Fixed in #424
