### ISSUE TITLE
Forecasted stock take in stock

### ISSUE THREAD

**Issue by amaroosolutions** [OCA/stock-logistics-workflow#419]
Hi, Great module but I have found a slight issue, With purchasing installed if you raise a PO for a product it is classing this as available stock but this could still be weeks away from delivery. Should it not look at the stock on hand figure rather than the forecasted quantity? 
Tested on V11

**Comment by pedrobaeza** [comment]
Which module?

**Comment by amaroosolutions** [comment]
Sorry the module is “Stock Disallow Negative”  (stock_no_negative) v11

**Comment by pedrobaeza** [comment]
That module is not taking into account forecasted quantity. Just it doesn't allow negative quants.
