### ISSUE TITLE
[10.0][stock_ownership_availability_rules]: incompatible with Perpetual inventory valuation

### ISSUE THREAD

**Issue by tafaRU** [OCA/stock-logistics-workflow#429]
The module `stock_ownership_availability_rules` seems to be incompatible with Perpetual inventory valuation. See https://github.com/odoo/odoo/blob/10.0/addons/stock_account/models/stock.py#L92 as reference.

With this module installed no accounting entries will be automatically created.

**Comment by rousseldenis** [comment]
@tafaRU Is this still relevant ? We did some changes in that module https://github.com/OCA/stock-logistics-workflow/commit/cb4819f500f944af6eff8d04c451e3b26437a4be#diff-75d8c25aa27e1e88f84970b25c375147
