### ISSUE TITLE
[11.0] stock_picking_invoice_link, picking link not removed when removing invoice line

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/stock-logistics-workflow#434]
When the invoice line of a related picking in an invoice is removed. The relation is not removed.

Reproduce:

1. create invoice from sale order with multiple deliveries
2. check how many pickings are linked
3. Remove one the invoice lines
4. Same amount of pickings are linked

**Comment by pedrobaeza** [comment]
Yeah, that's true, but you have to check that there are no other invoice lines also linked. Maybe you can propose a PR with these improvements, or at least, specifying this as a known issue.

**Comment by rousseldenis** [comment]
@mreficent @sergio-teruel  could you check at this ?

**Comment by rousseldenis** [comment]
@CasVissers Is this solved ?

**Comment by CasVissers-360ERP** [comment]
@rousseldenis I didn't solve it yet. Has no priority for the customer.
