### ISSUE TITLE
[IMP] product_serial: Add constraint to deny moves with qty <> 1 on product with unique serial

### ISSUE THREAD

**Issue by moylop260** [OCA/stock-logistics-workflow#45]
Hello,
I'm reviewed product_serial module to work with unique serial number.
But I don't found the way to work with this case.

Am I doing any bad?
Or this module is out of scope of this case?

I want dev this new feature but I'm confused of how add it.

1) I add a new module. (out of scope of product_serial module).
2) I make a pr with this feature to product_serial.

What do you think?

**Comment by gurneyalex** [comment]
@moylop260 make a PR.
