### ISSUE TITLE
Does this module work with refunded invoices?

### ISSUE THREAD

**Issue by natthanank** [OCA/stock-logistics-workflow#481]
It work when I create invoice normally, but when I create refund invoices  it doesn't work.

**Comment by rousseldenis** [comment]
@natthanank Hi! Could you please give more explanation and details about your problem? Which module do you want to use, which version,...

**Comment by natthanank** [comment]
I use stock_picking_invoice_link module in Odoo 10 :(

**Comment by bodedra** [comment]
@natthanank I have reviewed `stock_picking_invoice_link` module code and haven't found any evidence to support refund invoices.
