### ISSUE TITLE
stock_picking_backorder_strategy module fails to return backorder record 

### ISSUE THREAD

**Issue by b-kannan** [OCA/stock-logistics-workflow#495]
@api.multi
    def _create_backorder(self, backorder_moves=None):
        if backorder_moves is None:
            backorder_moves = []
        res = False
        # Do nothing with pickings 'no_create'
        pickings = self.filtered(
            lambda p: p.picking_type_id.backorder_strategy != 'no_create')
        pickings_no_create = self - pickings
        pickings_no_create.mapped('move_lines')._cancel_remaining_quantities()
        backorders = super(StockPicking, pickings)._create_backorder(
            backorder_moves=backorder_moves)
        to_cancel = backorders.filtered(
            lambda b: b.backorder_id.picking_type_id.backorder_strategy ==
            'cancel')
        to_cancel.action_cancel()
        return res

The above method should be returning backorders, not 'res'. So, please rename 'res' variable to 'backorders".

**Comment by rousseldenis** [comment]
I confirm the problem.

**Comment by rousseldenis** [comment]
Did the fix : #496

**Comment by rousseldenis** [comment]
:smile: @max3903

**Comment by max3903** [comment]
aha :) Up to you, man. No hard feeling.

**Comment by max3903** [comment]
Ah but yours is on v10... :+1:
