### ISSUE TITLE
Can't enforce internal traceability, even with product_serial

### ISSUE THREAD

**Issue by clonedagain** [OCA/stock-logistics-workflow#5]
For the moment there seems to be no clear way of forcing users to enter lots/serial numbers on internal moves (see https://bugs.launchpad.net/openobject-addons/+bug/670451).
product_serial does create a field "track_internal" with a helptext that says it forces users to enter the serial number, but I found no code to support that.

**Comment by clonedagain** [comment]
If there is no reference implementation in OCA, I can propose a very basic one and make product_serial depend on it.
Features would only be:
- add field "track_internal"
- add constraint to refuse internal stock moves without lots

**Comment by clonedagain** [comment]
Please remove the WIP tag. I'm not working on this anymore  - our PR was closed and we're moving to v8 where the feature is standard.
Feel free to close the issue if you feel "upgrade to v8" is a sufficient fix.

**Comment by rousseldenis** [comment]
I close this as it is very old and fix seems to have been provided
