### ISSUE TITLE
[11.0]Feature request: stock_no_negative, create product into stock.move.line if stock.qty <= 0 at the time of sale confirmation

### ISSUE THREAD

**Issue by mhdsyarif** [OCA/stock-logistics-workflow#504]
Feature request: stock_no_negative, create product into stock.move.line if stock.qty <= 0 at the time of sale confirmation.
-----
When making a Sale Order with product stock <= 0, then upon confirmation of sale, the product is not in stock.move.line

**Comment by rousseldenis** [comment]
Hi @mhdsyarif, thank you for your request.

Could you be a little bit more explicit on the flow you are testing? Maybe, you could add some screenshots ?

Thanks

**Comment by mhdsyarif** [comment]
Hi @rousseldenis,
Scenario in video
[https://drive.google.com/open?id=1KcmSiqzi8-HCEtjJnVUOOmVftjqcYmfOv](url)
Thanks

**Comment by pedrobaeza** [comment]
I think this has nothing to be with `stock_no_negative` module.

**Comment by mhdsyarif** [comment]
Hi @pedrobaeza,
Yes, can you help me to create a new module based on the video above.
Thanks.

**Comment by pedrobaeza** [comment]
Sorry, but teaching you in that is so wide that can't be done.
