### ISSUE TITLE
[12.0] Migration stock_no_negative

### ISSUE THREAD

**Issue by meigallodixital** [OCA/stock-logistics-workflow#507]
I am migrating stock_no_negative to 12.0, and while it detects the negative stock and raise the validation error, lets follow and sell stock that we do not have.

I do not know if this is the use case and I have misunderstood the module behaviour, or it is a bug. I understand that a ValidationError should block the operation, right?

**Comment by pedrobaeza** [comment]
Is this happening also in v11? If so, then the module can be incorrect or it's the intended behavior (which I doubt). If it's happening in v12 in your migration, then the migration is incorrect :wink:

**Comment by meigallodixital** [comment]
You're right, in 11.0 the behavior is the same. 

I thought that stock control was done at the time of the sale order line, but it is done when the order is delivered, at that time if it is not allowed to continue. In fact, I just notice that the message is not the same.

Even so, if we have marked the "Buy" route, it would not be interesting to stop creating that line, in the case of "Make to order" and "Dropshiping" the same behavior as now.

**Comment by pedrobaeza** [comment]
Indeed, the error is risen when the actual stock decreasing is done, which is validating the picking. For what you want, check `sale_exception` module with a predefined rule that comes with it.
