### ISSUE TITLE
Easy way to work with Product Kit in Delivery Order

### ISSUE THREAD

**Issue by ghost** [OCA/stock-logistics-workflow#530]
We have a need and are about to create a module "stock_sale_product_kit_move_helper"
The objective of this module is to add helper way to allow user to select partial shipment of product kit (BOM kit) in delivery order.

Given a product kit K1, its bom consist of P1 = 20 unit + P2 = 30 units

**Standard Odoo:**
- Sale order with K1 = 10 units
- DO will be created with detailed products, P1 = 200 and P2 = 300
- If user want to delivery 2 units of K1, user will manually key P1 = 40 and P2 = 60.

This is both difficult and error prone when doing partial delivery, and will be more difficult when > 1 product kits, each with intersection of detailed product.

**With the helper:**
- Sale order with K1 = 10 units
- DO will be created with detailed products, P1 = 200 and P2 = 300
- User use helper (i.e., wizard) to delivery 2 units of K1, and system will automatically fill in P1 = 40 and P2 = 60

This should be easier, at the same time, it do not change any core process.

**Question:**
- Is the addon name "stock_sale_product_kit_move_helper" make sense ?
- This module should be in stock-logistics-workflow, or stock-logistics-warehouse ?
- Or are there better way to deal with this ?

**Comment by rousseldenis** [comment]
@kittiu-ecosoft workflow repo makes sense.

I think the process could be more generic as you maybe want to change a simple picking.

So, the idea should be modifying picking with the helper and then, see if something should be implemented in another module for sale workflow.

'stock_picking_product_kit_helper or...' should be correct for the base module (look for non existing module in other repositories before).

But I like the idea

**Comment by ghost** [comment]
@rousseldenis thank you for your encouraging comment. I work something out first, and I hope you will give more comment there.
Note: I don't see what will related to sale workflow as you has mentioned yet. But let my feet wet first. :)

**Comment by kittiu** [comment]
@rousseldenis I am quite finish with the first draft. Here is how it works, feel free to comment. Given the following sample.

1) A sales order with 1 product kit.

![image](https://user-images.githubusercontent.com/1973598/59050940-decdd400-88b5-11e9-9b8c-1cfe8b4b1dab.png)

2) DO created as exploded lines

![image](https://user-images.githubusercontent.com/1973598/59050966-f1e0a400-88b5-11e9-9cd7-e6a00e923805.png)

3) Only if there is any product kit (check in sale_order_line), this new tab appear.

![image](https://user-images.githubusercontent.com/1973598/59051011-16d51700-88b6-11e9-974b-80447640637a.png)

4) User click to "Show Product Kit", fill quantity and set "Assign Operation Quantity"

![image](https://user-images.githubusercontent.com/1973598/59051051-31a78b80-88b6-11e9-9384-98edceb22066.png)

![image](https://user-images.githubusercontent.com/1973598/59051094-45eb8880-88b6-11e9-8d53-aed549edd8e1.png)

5) Quantity will be assigned to the Operation tab

![image](https://user-images.githubusercontent.com/1973598/59051112-53a10e00-88b6-11e9-8df6-6779e0a7b8b3.png)

**Comment by kittiu** [comment]
I have finished development with test script.
https://github.com/OCA/stock-logistics-workflow/pull/533
