### ISSUE TITLE
Translations for stock_batch_picking not synchronized on Weblate

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-workflow#543]
@sbidoul I have a weird case with this module. POT file was updated by my colleague @sergio-teruel directly in the pull request commit: f23c167e7cba79aae405204308890b6f7241268.

First of all, the bot makes another POT update commit, but with no real content: db442b1b225f925dedb4b6507ad545603f34928d, but I suppose we can't avoid this.

The real problem is that there's no reflect of the POT changes on the translation files, and thus, we can't translate new strings in Spanish for example: https://translation.odoo-community.org/projects/stock-logistics-workflow-11-0/stock-logistics-workflow-11-0-stock_batch_picking/es/#repository

When does the synchronization perform?

**Comment by sbidoul** [comment]
It should have been done by the msgmerge addon in weblate.
Unfortunately it does not always trigger, and from time to time I launch it with a script.

There must be a pattern of when it works and when it does not but I've not identified it so far.

**Comment by sbidoul** [comment]
I'll open an issue at weblate to try to make progress... although I've not much to say in terms of how to reproduce the bug...

**Comment by pedrobaeza** [comment]
OK, thanks for the insights. Can you share the script or give me the instructions on how to run it on the server for being able to launch it myself if I detect again the problem?
