### ISSUE TITLE
v12 picking: how to accelerate delivery encoding with huge lines number and lots

### ISSUE THREAD

**Issue by bealdav** [OCA/stock-logistics-workflow#551]
Use case v12:
My customer deal with lots and a have a lot of lines in its picking out
and complains of a very painful workflow.

Facts: 
1/ when you don't make any update on your picking (all products are available, all proposed lots are available), aka default data are untouched there are no waste of time.
2/ when you just modify one line (change lot) odoo propose to send only 1 line (the changed one) and put others in backorder or no backorder. All untouched lines are not proposed to be include in delivery with default data automatically. 

In case 2/ the most used, there are a lot of waste of time because you need to update all the lines even when default data are exact.

Do you know if your customers are in the same situation ?
May be I missed something ?

What the better way to make a better process ?

**Comment by bealdav** [comment]
Please do you share the same facts
@rousseldenis @mreficent @kittiu @lreficent @carlosdauden

**Comment by carlosdauden** [comment]
Something like this would help you?
https://github.com/OCA/stock-logistics-workflow/tree/11.0/stock_pack_operation_auto_fill

**Comment by pedrobaeza** [comment]
For v12 is called `stock_move_line_auto_fill`

**Comment by carlosdauden** [comment]
https://github.com/OCA/stock-logistics-workflow/pull/538

**Comment by bealdav** [comment]
Thanks a lot. 
I've missed smth. It's a fact ;-)
