### ISSUE TITLE
[10.0] [stock_cancel] doesn't delete related quants when cancelling stock picking

### ISSUE THREAD

**Issue by bharatrdevnani** [OCA/stock-logistics-workflow#556]
Hi Community Members,

I tried receiving the shipment for an item, and appropriate stock moves and quants were registered. but when I reopened and cancelled the picking, the stock.quants are still there but at source location which is Vendors Location.

Is this correct behavior ? shouldn't it delete the quants ?

BR,
Bharat

**Comment by AaronHForgeFlow** [comment]
This is intended behavior. The quant actually exists but in the previous location.
