### ISSUE TITLE
[7.0] [product_customer_code_picking] Error accessing to the picking associated to a manufacturing order

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/stock-logistics-workflow#56]
Hello, 
When you try to access to the picking associated to a manufacturing order, that has no partner, the following error appears:

stock-logistics-workflow/product_customer_code_picking/stock_picking.py", line 35, in _get_product_customer_code
    move.picking_id.partner_id.commercial_partner_id.id)
AttributeError: 'NoneType' object has no attribute 'id'

I will be providing a PR that fixes this issue.

**Comment by eLBati** [comment]
Hi @jbeficent can this be closed?

**Comment by JordiBForgeFlow** [comment]
Yes, I'm closing.
