### ISSUE TITLE
[11.0] Create packages in stock_batch_picking

### ISSUE THREAD

**Issue by carlos-domatix** [OCA/stock-logistics-workflow#571]
It is possible to create packages with the module stock_batch_picking as in the Odoo transfers (With button "Put in pack")? Thanks.

**Comment by rousseldenis** [comment]
@sergio-teruel You can maybe help here ?

**Comment by sergio-teruel** [comment]
Hi @carlosDomatix  What do you want to do exactly? Create a package from one batch picking?
