### ISSUE TITLE
[12.0] [stock_picking_package_preparation/line] Slow and product_uom_qty same as qty done

### ISSUE THREAD

**Issue by hustlercoder** [OCA/stock-logistics-workflow#573]
When using this module with a lot of rows for wh/in or wh/out the waiting time is so long.
Anyway this is not a problem for now...but the real question is why the pack_done put the qty_done equal to product_uom_qty also if there is a stock.move.line with a different qty

**Comment by rousseldenis** [comment]
@eLBati @tafaRU @SimoRubi Maybe you'll have an answer for this ?

**Comment by SimoRubi** [comment]
Hi @hustlercoder,
could you please post the steps and the actual/expected behavior to help us understand your issue?
Thanks!

**Comment by hustlercoder** [comment]
@SimoRubi  Yes so the actual problem was that the module put the qty_done equal to the product_uom_qty also if you leave it at 0...and this is wrong...and no sense...but i manage this..I removed the condition in the module...now the question is..i have some WH/IN that are between 1000/1200 rows of products(due to migration from another crm to odoo)...and when i click put in pack...it takes something like 30 min to complete...when i read the log i can see a lot of stock.package.preparation.line which are deleted

**Comment by SimoRubi** [comment]
Thanks, so the issue now is that when you click "Put in pack", it takes very long for many rows and all you see in the logs is preparation_lines being deleted.

I just tried that in my local environment and it does not delete any preparation line when clicking on "Put in pack".
On the other hand I noticed that those lines are being deleted after clicking on "Package done" button, could you confirm that?

**Comment by hustlercoder** [comment]
@SimoRubi  yes on the first attempt it was on put in pack but now i can confirm that on pack done is the problem

**Comment by hustlercoder** [comment]
@SimoRubi still alive?

**Comment by SimoRubi** [comment]
yess, I'll look into this when I can

**Comment by ovscorp** [comment]
Was there any solution for this issue. I am facing a similar problem when validating a picking with 700 lines. The picking is never validated (even after 1 hour). The log shows thousands of deleting event :
...
2021-05-04 11:59:03,378 6404 INFO mydb odoo.models.unlink: User #2 deleted stock.picking.package.preparation.line records with IDs: [62793] 
2021-05-04 11:59:03,475 6404 INFO mydb odoo.models.unlink: User #2 deleted stock.picking.package.preparation.line records with IDs: [62794] 
2021-05-04 11:59:03,568 6404 INFO mydb odoo.models.unlink: User #2 deleted stock.picking.package.preparation.line records with IDs: [62795] 
2021-05-04 11:59:03,719 6404 INFO mydb odoo.models.unlink: User #2 deleted stock.picking.package.preparation.line records with IDs: [62796] 
 
It seems like it is turning in circle.
I am using odoo 12 CE.

**Comment by eLBati** [comment]
Sorry, do we have the steps to reprodice this?

**Comment by ovscorp** [comment]
I've created a PO with 700 lines, validate it. Then, when confirming the picking, it was turning with no end. Please note that there is no issue if the number of lines in the picking is not huge.
If there is an odoo instance where I can reproduce this, please share.

**Comment by eLBati** [comment]
The OCA runbot https://runbot.odoo-community.org/runbot/repo/https-github-com-oca-stock-logistics-workflow-154
Thanks

**Comment by sergiocorato** [comment]
Do you have many other sppp ready or draft? I saw this [part](https://github.com/OCA/stock-logistics-workflow/blob/12.0/stock_picking_package_preparation_line/models/stock_move.py#L21..L39) is very time consuming in some cases.

**Comment by ovscorp** [comment]
Hi, The bug is happening only with 'several lines picking'. I am not able to reproduce this in runbot by importing a big picking. I will setup an odoo session on a vps and share credentials with you.
