### ISSUE TITLE
[11.0] stock_picking_invoice_link

### ISSUE THREAD

**Issue by Joaco1980** [OCA/stock-logistics-workflow#578]
When there are returns of delivery notes they do not appear in the list of delivery notes. 
If invoices with positive and negative quantities to avoid making credit invoices

**Comment by pedrobaeza** [comment]
Unless you explain a bit more the steps to reproduce the problem, this is not enough for understanding the issue.

**Comment by Joaco1980** [comment]
SO001 - WH/OUT/001 y WH/OUT/002
SO002 - WH/OUT/003
SO003 - WH/OUT/004

Now return one product WH/OUT/002 y create WH/IN/001

Invoice all Sales Order, in the list of picking, the return does not appear
