### ISSUE TITLE
[12.0][ stock_picking_mass_action] force picking

### ISSUE THREAD

**Issue by eguane** [OCA/stock-logistics-workflow#587]
HI, after installation, I can't show force picking in the action wizard ?

"A wizard which allows on multiple stock pickings at a time to:

Confirm draft picking;
check availability of picking;
force availability of picking;
transfer picking; "

**Comment by rousseldenis** [comment]
See https://github.com/OCA/stock-logistics-workflow/pull/534/commits/4d4aff10c074500f16b07ac06293a9ac3634043a

As force availability is not anymore on v12, the functionnality has disappeared but stay in README.

@carlosdauden Could you fix README ?

**Comment by eguane** [comment]
Ok, clear.

Thank for your feedback.

**Comment by quentinDupont** [comment]
> See [4d4aff1](https://github.com/OCA/stock-logistics-workflow/commit/4d4aff10c074500f16b07ac06293a9ac3634043a)
> 
> As force availability is not anymore on v12, the functionnality has disappeared but stay in README.
> 
> @carlosdauden Could you fix README ?

Hello !

But... why did that feature disappear?
Our activities in Odoo cannot have their stock permanently updated (with just one purchase order that has not yet been processed..) and therefore they cannot easily validate their sale..? There is something I may be missing?
