### ISSUE TITLE
Couldn't process Purchase workflow

### ISSUE THREAD

**Issue by jiad** [OCA/stock-logistics-workflow#618]
I have installed this module, but found that the "receive product" >> validate >> Apply all product,  not work. No respon at all.

Anyone know how to change back the normal purchase workflow??
Thanks.

**Comment by jiad** [comment]
the module i installed is stock_batch_picking

**Comment by pedrobaeza** [comment]
You are not even indicate the Odoo version and the steps to reproduce the problem are not enough. Please indicate all of them, from the beginning. Closing meanwhile.

**Comment by jiad** [comment]
sorry. my bad. I am using odoo 9. I have installed the module stock_batch_picking and stock_picking_wave. And had some operations with these two modules to receive the purchase products. BUT after I have uninstalled them both, and I can't install them back anymore. It showed error below: 

> The operation cannot be completed, probably due to the following:
> - deletion: you may be trying to delete a record while other records still reference it
> - creation/update: a mandatory field is not correctly set
> 
> [object with reference: stock_picking_wave - stock.picking.wave]
> you have to delete the records that are created by installing the module

And in purchase module, I can make and confirm purchase orders, but it couldn't finish the workflow as I can't receive the products.
