### ISSUE TITLE
build broken by recent changes in odoo/odoo

### ISSUE THREAD

**Issue by gurneyalex** [OCA/stock-logistics-workflow#66]
Commit https://github.com/odoo/odoo/commit/675357b7d7b broke the build by causing failures in the tests of stock_dropshipping_dual_invoice

https://travis-ci.org/OCA/stock-logistics-workflow/jobs/50039271#L313

**Comment by gurneyalex** [comment]
@lepistone could you check whether this is an issue in stock_dropshipping_dual_invoice or in odoo/odoo?

**Comment by lepistone** [comment]
It is indeed a regression introduced yesterday. I pinged Olivier who is fixing it, so probably no need for a PR or issue. I'll report back here.

**Comment by lepistone** [comment]
It is now fixed, and the fix has been propagated to OCB.
