### ISSUE TITLE
[12.0] stock_picking_invoice_link : restore related links after update module

### ISSUE THREAD

**Issue by josepmy** [OCA/stock-logistics-workflow#665]
Hi,
Any workaround to restore the previous links related to  stock_picking_invoice_link after update the module? 

Thanks,
Josep M

**Comment by pedrobaeza** [comment]
No, as it can't be done as the information can't be deduced post-mortem. You can guess in the best case if everything is invoiced at once and only one involved picking, but it's going to be partial and not done for now.

**Comment by josepmy** [comment]
Why partial? Restoring account_invoice_stock_picking_rel the pickings appear again related to their invoice. I guess it is all completed, but the PDF grouped by picking now is related a new table stock_move_invoice_line_rel where insert the invoice_line_id with their stock move_id, so I guess it could be restored with a script, right?

**Comment by pedrobaeza** [comment]
No, it can't be. You can deliver several times, but invoice one, or deliver one, return, invoice, refund, invoice again, etc. All of this can't be deduced post-mortem.

**Comment by josepmy** [comment]
Agree, I understand it, this from now, but for the old data if I restore it, this will be the information I had, right? and the customer could see that, better that not seeing nothing.

**Comment by pedrobaeza** [comment]
OK, go ahead and contribute with that initialization script :wink:

**Comment by josepmy** [comment]
Ok, I will try it. But the point of view of restoring the account_invoice_stock_picking_rel, that after the module update is empty, with the previous values is correct, right?

**Comment by pedrobaeza** [comment]
There are other fields to fill, but I don't have them in mind just now (m2m at invoice and line level at least). Check which fields add this module.
