### ISSUE TITLE
[12.0] stock_picking_invoice_link: Error: Unknown field location_dest_id in domain

### ISSUE THREAD

**Issue by gertcuykens** [OCA/stock-logistics-workflow#676]
`Stock Picking Invoice Link` v12.0.2.0.0 gives the following error `"Unknown field location_dest_id in domain"` 

Example when you click on invoices

![image](https://user-images.githubusercontent.com/863731/86197223-3ab86a00-bb55-11ea-819c-72883dacb005.png)

<img width="1440" alt="Screenshot 2020-07-01 at 04 26 48" src="https://user-images.githubusercontent.com/863731/86196816-540ce680-bb54-11ea-9c5e-3b7305399297.png">

![image](https://user-images.githubusercontent.com/863731/86197323-705d5300-bb55-11ea-8b26-fce40c002f87.png)

[bug1.txt](https://github.com/OCA/stock-logistics-workflow/files/4855310/bug1.txt)

Note this is probably because there is some incomplete record fields from either the test product or test customer. But this shouldn't let the client crash and provide message what record needs to be modified.

**Comment by pedrobaeza** [comment]
There's no such domain in the module, so the problem should come from other third party module you have. Check on the runbot link in the module README that everything is working correctly.

Closing as no issue at this module.

**Comment by gertcuykens** [comment]
Ok thanks, you are correct, apparently when I remove every custom addon I don't have a error msg anymore.
