### ISSUE TITLE
Odoo.sh install, error (post-migrated) version 12.0

### ISSUE THREAD

**Issue by elhamdaoui** [OCA/stock-logistics-workflow#680]
ERROR | server | 
module stock_picking_invoice_link: Each post-migration file must have a "migrate(cr, installed_version) function

**Comment by pedrobaeza** [comment]
Sorry, but the restriction seems incorrect on Odoo.sh part, not on the module. We are decorating the function with a special decorator and the signature is not going to be that one, as we switch `cr` by `env`.
