### ISSUE TITLE
[12.0] Addon exist related to picking_note in sale order?

### ISSUE THREAD

**Issue by victoralmau** [OCA/stock-logistics-workflow#683]
I have implemented an addon that adds a field in the sale_order called picking_note, so that that field (text) is added to the stock_picking as a relational field.

It is useful since things would be specified there regarding the preparation of the order in the warehouse.
Does this already exist in any addon or is it an addon that could be contributed to the repository? I think it would be called: stock_picking_sale_order_note

**Comment by rafaelbn** [comment]
Take a look here: 

https://github.com/OCA/sale-workflow/tree/10.0/sale_stock_picking_note

https://github.com/OCA/sale-workflow/tree/12.0/sale_stock_picking_note

**Comment by pedrobaeza** [comment]
And https://odoo-community.org/shop/product/picking-comments-4821

**Comment by victoralmau** [comment]
Ok, thank you very much, in this case the addon **sale_stock_picking_note** is exactly what I was looking for.
