### ISSUE TITLE
[12.0] Addon exist related to carrier_note in sale order?

### ISSUE THREAD

**Issue by victoralmau** [OCA/stock-logistics-workflow#684]
I have implemented an addon that adds a field in the sale_order called carrier_note, so that that field (text) is added to the stock_picking as a relational field.

It is useful since things would be specified there for the carrier (deliver at 08:00, leave the neighbor, etc.)
Does this already exist in any addon or is it an addon that could be contributed to the repository? I think it would be called: stock_picking_sale_order_carrier_note

Maybe this addon corresponds to the repository https://github.com/OCA/delivery-carrier (I'm not sure)

**Comment by pedrobaeza** [comment]
I would use other general modules like sale_stock_picking_note or stock_picking_comment_template. No need to create a specific one IMO.

**Comment by victoralmau** [comment]
I have seen the addons you suggest and each one is useful for its function; that is to say, the addon **sale_stock_picking_note** would help define a comment from the sale_order "_Cut the merchandise in this way_", but regarding the integration of other carriers with the addon https://github.com/OCA/delivery-carrier/tree/12.0/base_delivery_carrier_label requires additional notes that must be configured from the sale_order "_Deliver at 08:00 or deliver to neighbor_".
They should be separate notes since many times these comment fields have limited characters (due to integration with transport companies).

All this related to https://github.com/OCA/stock-logistics-workflow/pull/679 and integrations with carriers that require a "carrier comments" field.

**Comment by pedrobaeza** [comment]
Yeah, I see the purpose now. Which are the carriers that use it?

**Comment by victoralmau** [comment]
The new addons that these fields will need are:
- delivery_cbl (fields: observations1 and observations2) Field limit to 100 characters
- delivery_nacex (fields: obs1, obs2, obs3 and obs1) Field limit to 38 characters
- delivery_txt (fields: observations1 and observations2) Field limit to 100 characters
- delivery_tsb (field: observations) Field limit to 250 characters

The character limit will be made in each of the addons "dividing" the text of the comments in as many fields as appropriate.

It is for this reason that he indicated that perhaps an addon for this would be useful and added as a dependency in these new addons.

**Comment by pedrobaeza** [comment]
Yes, it can be planned that way. Note than most of the carriers simply introduces a field for that, and having "templates" for that can be both good and bad, as if you have a lot of templates, it will be a mess to find the suitable one and you take less time writing on your own. Anyway, the result should go to OCA/delivery-carrier.

**Comment by victoralmau** [comment]
Ok, thank you very much, I had also thought about making a field of observations for each carrier but as you indicate it would be somewhat complicated to know which field should be filled in the sale_order (and if sometimes a carrier is not defined in the sale_order it would be impossible to know which one) .

All cleared up, an addon will be created at https://github.com/OCA/delivery-carrier called: **delivery_carrier_label_note**

**Comment by victoralmau** [comment]
I have created the PR https://github.com/OCA/delivery-carrier/pull/273 for this issue.
