### ISSUE TITLE
[12.0] Addon update carrier_id in sale_order when stock_picking done?

### ISSUE THREAD

**Issue by victoralmau** [OCA/stock-logistics-workflow#685]
I have implemented a small addon that when the stock_picking is validated, update the carrier_id of the corresponding sale_id by the corresponding one (since sometimes in the sale_order carrier_id is not specified and it should be updated with the corresponding carrier in the sale_order so that this information is updated and reflected in the corresponding invoice.

Is there a similar addon or could it be added to the repository? I think it would be called: stock_picking_done_update_carrier_in_sale_order

**Comment by pedrobaeza** [comment]
https://github.com/OCA/delivery-carrier/tree/12.0/delivery_auto_refresh is for the same goal.

**Comment by victoralmau** [comment]
First of all thank you very much for the suggested addon.

I've tested the addon in detail and I've seen that some things it doesn't:
- If a carrier with price 0 is defined in the stock_picking, it does not put that line in the sale_order
- Any carrier that is defined in stock_picking does not update the carrier_id field in the sale_order

Is this really an addon bug or is this just not covered?

**Comment by pedrobaeza** [comment]
> If a carrier with price 0 is defined in the stock_picking, it does not put that line in the sale_order

If I don't remember bad, that was the expected behavior for the customer we developed the module to.

> Any carrier that is defined in stock_picking does not update the carrier_id field in the sale_order

What is the purpose of doing this?

**Comment by victoralmau** [comment]
For the use that we give it, it is wanted that both if a carrier has been defined in the sale_order (sometimes in the stock_picking it changes from carrier_id) as if none had been defined, you want that information to be updated in the sale_order set that information of the sale_order is consulted and it is analyzed by which carrier_id they have left and by province (for example).

Clarify that in our case the transport has no cost and / or if it does not have to "change" with respect to what the client has already accepted in the sale_order.

**Comment by pedrobaeza** [comment]
Well, it seems a use a bit marginal, but it can be added to existing module through a parameter (or unconditionally, to be analyzed).
