### ISSUE TITLE
Sequence number starts from 9,999 for single item in Delivery Slip

### ISSUE THREAD

**Issue by amnyqb** [OCA/stock-logistics-workflow#696]
module: stock_picking_line_sequence
version: 12.0

**Steps to reproduce**
Installation of Sales Order Sequence, Procurement and Picking Sequence modules (from OCA)
Create and confirm a sale order with a single item, print Delivery Slip

**Current behavior**
The sequence column shows in the Delivery slip, however, the sequence number starts from 9,999

**Expected behavior

Sequence number should start from 1

[Delivery Slip - Deco Addict - WH_OUT_00004.pdf]
(https://github.com/OCA/stock-logistics-workflow/files/5113761/Delivery.Slip.-.Deco.Addict.-.WH_OUT_00004.pdf)

**Comment by nikul-serpentcs** [comment]
@amnyqb Here I think added default sequence like this https://github.com/OCA/stock-logistics-workflow/blob/12.0/stock_picking_line_sequence/models/stock.py#L14

**Comment by amnyqb** [comment]
@nikul-serpentcs Thank you Nikul, 
Do you mean, you've made changes to the code, or it runs fine with you as it was?

**Comment by amnyqb** [comment]
I noticed that this error occurs after installing the other OCA modules for sequence numbering ( for Invoice/Sales..)
It works fine when it is installed on its own (with the other dependencies of course)

**Comment by AaronHForgeFlow** [comment]
The default is 9999, because if the default is 1 then all the lines will be added on the top not at last, and that would be changing the standard behavior and that is not the purpose of the module. When saving the picking the sequence will be the correct one. Perhaps this is not the ideal solution but the other option is not acceptable.
