### ISSUE TITLE
stock_ownership_availability_rules disables stock accounting

### ISSUE THREAD

**Issue by yostashiro** [OCA/stock-logistics-workflow#74]
No journal entry gets generated for stock valuation from receipt/delivery after installing this module even when the owner of the stock is the company.

According to stock_account module, accounting valuation entry is designed not to be generated in case a quant has an owner.
https://github.com/odoo/odoo/blob/8.0/addons/stock_account/stock_account.py#L113

**Comment by yostashiro** [comment]
A module to fix the issue (temporary use): https://github.com/rfhk/awo-custom/tree/master/stock_account_adjust

**Comment by lepistone** [comment]
Thanks @yostashiro for the report!

Indeed the module makes the owner required, using the current company as owner by default, so that line needs to be changed to something like 

``` python
if quant.owner_id and quant.owner_id != current_company.partner_id
```

However, this is a long method, and to change that line, we'll probably have to duplicate the whole method.

Any ideas? (ping @gurneyalex)

**Comment by lepistone** [comment]
I can't think of a more clever fix than to redefine the whole method with that line changed. If you could make a pull request towards `stock-ownership-availability-rules` I'd be glad to review it. Thanks!

**Comment by yostashiro** [comment]
Hi @lepistone,
I could not think of a better way to handle the issue.  Appreciate your review.

**Comment by gurneyalex** [comment]
@lepistone maybe a PR on odoo could be made for this?

(cc @jgrandguillaume)

**Comment by pedrobaeza** [comment]
Added a warning in the README in 523555fd72d381ec7ca59b0900580cda122aa13a
