### ISSUE TITLE
review field name lngth in length

### ISSUE THREAD

**Issue by andreampiovesana** [OCA/stock-logistics-workflow#778]
module: stock_quant_package_dimension
version: 13.0

suggest to rename lngth in length,
and better to prefix with pack_ like pack_weight

**Current behavior**
lngth
width
height
volume

**Expected behavior**
pack_length
pack_width
pack_height
pack_volume

**Comment by pedrobaeza** [comment]
A field can't be named as `length`, as it's a reserved word.

**Comment by andreampiovesana** [comment]
Infact i suggested pack_length
