### ISSUE TITLE
[13.0] stock_picking_invoice_link not show all related invoices on picking

### ISSUE THREAD

**Issue by sergioeix** [OCA/stock-logistics-workflow#780]
Steps to reproduce:
1-Make a sale of stockable product 2 und
2-Do the picking delivery for the 2 und
3-Sale order is up to invoice, but on invoice decrease qty and do 1 und invoice
4-Sale order is still up to invoice, then do the invoice for the remain 1 und
5-At this point we have 2 invoices on the same picking, go to the picking and click on invoices smart button
6-Only the first invoice form its shown

Spected behaivor:
a tree view with the 2 related invoices

Ty

**Comment by rousseldenis** [comment]
@manuelcalerosolis

**Comment by manuelcalerosolis** [comment]
From the module documentation

Usage
Create a Sales Order and confirm.
Deliver its pickings totally or partially.
Create an invoice of the goods delivered.
If you open invoice form, you must see a new Pickings tab with information about them.
