### ISSUE TITLE
Migration of product delivery window is not in the list of migration to v14

### ISSUE THREAD

**Issue by Stephanisk** [OCA/stock-logistics-workflow#856]
I was looking to install the product delivery window module for v14 but was surprised to not find it and also didn't find it in the current migration list.

I hope someone has some extra time left to have a look for this migration. It is a super important part of stock workflows to know when products can be delivered to a partner.

Quite surprised that no-one has raised this issue before.

**Comment by rousseldenis** [comment]
Hi @Stephanisk, the migration list is generated once based on v13 already migrated modules. It is not updated with new merged ones.

As this is based on contributors needs, maybe nobody has it until now. You can for sure propose a PR to migrate it.
