### ISSUE TITLE
[14.0] stock_picking_filter_lot applying on all picking types not only outgoing

### ISSUE THREAD

**Issue by remi-filament** [OCA/stock-logistics-workflow#865]
Although stock_picking_filter_lot states the following in README : in a picking **out** or a scrap, the domains applied seem not limited to outgoing picking but applies on any picking.

The following use case is then not working for me :
I receive for the second time product from supplier (from Vendor location) with already existing lot number. In that case, the lot_id field does not propose any SN (since there are none in Vendor location), but I also cannot create a new lot number since it already exists...

I am not sure what should be the best way-forward ?
I was thinking at first to enforce domain only for outgoing picking, but it could definitely make sense for internal (at least some of those) and even incoming when you receive back from customer, you could filter to get only delivered lots...
Maybe it should be an option on stock picking type whether to apply filter or not ?

As far as I could tell, this is the same since version 10.0 of this module

**Comment by gdgellatly** [comment]
by default in odoo, incoming operations do not allow existing lots. you must explicitly allow it. your report does not state whether you have or not.

**Comment by remi-filament** [comment]
Hi @gdgellatly thank you for looking into it.
Yes I have allowed both existing lots and creating new lots.

The issue is related to the domain condition added  by stock_picking_filter : ('location_ids', 'child_of', location_id)
When receiving lots already created in system, they for sure do not have a location_id set and therefore would not be shown in the list.

Since it is not found, you need to create a new lot, which is failing because lot already exists.


I am not sure how to overcome this issue, maybe we need to add an extra boolean on stock_location_type (for instance "Use available lots only") and apply domain only if this is True ?
If this makes sense for community, I could create a PR but I actually do not know technically how to apply domain only if a variable is True. Any help welcome here !

**Comment by remi-filament** [comment]
Found a solution by using web_domain_field see #894
