### ISSUE TITLE
[12.0-15.0] stock_no_negative : fr.po translation accents

### ISSUE THREAD

**Issue by remihb** [OCA/stock-logistics-workflow#990]
## stock_no_negative
I noticed that since version 12.0 of the module, there is some problems in translations.
In `i18n/fr.po` file, you can see entries like
```
msgid "Allow Negative Stock"
msgstr "Autoriser le stock n??gatif"
```
Do I have to modify it manually and make a PR for that ?

**Comment by rousseldenis** [comment]
> ## stock_no_negative
> I noticed that since version 12.0 of the module, there is some problems in translations. In `i18n/fr.po` file, you can see entries like
> 
> ```
> msgid "Allow Negative Stock"
> msgstr "Autoriser le stock n??gatif"
> ```
> 
> Do I have to modify it manually and make a PR for that ?

You can do it there: https://translation.odoo-community.org/
